---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: dummkopf
spec:
  replicas: 10
  syncPolicy:
    automated: {}
  selector:
    matchLabels:
      app: dummkopf
  template:
    metadata:
      labels:
        app: dummkopf
    spec:
      containers:
        - name: dummkopf
          image: 920858517028.dkr.ecr.us-east-1.amazonaws.com/dummkopf:0.0.7
          ports:
            - containerPort: 9000
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
        - setWeight: 10
        - pause:
            duration: 20
        - setWeight: 20
        - pause: {}
